import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import type { PluginOptions as SearchPluginOptions } from '@easyops-cn/docusaurus-search-local';
import type { NormalizedSidebar, NormalizedSidebarItem, NormalizedSidebarItemCategory, SidebarItemDoc, SidebarItemsGeneratorOption } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

type SidebarItemsGeneratorArgs = Parameters<SidebarItemsGeneratorOption>[0];

const config: Config = {
  title: 'r/JapanFinance',
  tagline: 'Finance & Tech in Japan',
  favicon: 'img/favicon.ico',

  // Set the production url of your site here
  url: 'https://wiki.japanfinance.org',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/',

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'JapanFinance', // Usually your GitHub org/user name.
  projectName: 'wiki', // Usually your repo name.

  // GitHub Pages adds a trailing slash to Docusaurus URLs by default. It is recommended to set a trailingSlash config (true or false, not undefined).
  trailingSlash: true,

  onBrokenLinks: 'warn', // TODO switch to 'throw' after addressing broken links

  future: {
    // See https://docusaurus.io/blog/releases/3.8#future-flags
    v4: true, // Enable Docusaurus v4 features
    // See https://docusaurus.io/blog/releases/3.6
    experimental_faster: true
  },

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    }
  },

  presets: [
    [
      'classic',
      {
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          editUrl: ({ docPath }) =>
            `https://old.reddit.com/r/JapanFinance/wiki/edit/index/${docPath.includes("index") ? '' : docPath.slice(0, docPath.lastIndexOf('.'))}`,
          async sidebarItemsGenerator({ defaultSidebarItemsGenerator, ...args }: SidebarItemsGeneratorArgs): Promise<NormalizedSidebar> {
            const sidebarItems = await defaultSidebarItemsGenerator(args);
            return updateAutogeneratedSidebarForRedditWikiStructure(sidebarItems);
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        // `hashed` is recommended as long-term-cache of index file is possible.
        hashed: true,
        language: ['en', 'ja'],
        docsRouteBasePath: '/',
        indexBlog: false, // blog is disabled
      } satisfies SearchPluginOptions,
    ],
    '@docusaurus/theme-mermaid',
  ],

  themeConfig:
    {
      announcementBar: {
        content: '🧮 Check out the <a href="https://kei3.japanfinance.org" target="_blank">Calculator</a>! 🧮',
      },
      colorMode: {
        respectPrefersColorScheme: true,
      },
      metadata: [{ name: 'keywords', content: 'finance, japan, tax, personal finance, income, retirement, FIRE' }],
      // Your project's social card
      image: 'img/social-card.jpg',
      navbar: {
        title: 'r/JapanFinance',
        logo: {
          alt: 'r/JapanFinance',
          src: 'img/logo.svg',
        },
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'wikiSidebar',
            position: 'left',
            label: 'Wiki',
          },
          {
            href: 'https://kei3.japanfinance.org',
            position: 'left',
            label: 'Calculator',
            'aria-label': 'JapanFinance Calculator',
            rel: '',
          },
          {
            href: 'https://www.reddit.com/r/JapanFinance/',
            position: 'right',
            className: 'header-reddit-link',
            'aria-label': 'r/JapanFinance subreddit'
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              {
                label: 'Wiki',
                to: '/',
              },
            ],
          },
          {
            title: 'Community',
            items: [
              {
                label: 'Reddit',
                href: 'https://www.reddit.com/r/JapanFinance/',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} r/JapanFinance contributors. Built with Docusaurus.`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    } satisfies Preset.ThemeConfig,
};

export default config;

function isSidebarDocItem(item: NormalizedSidebarItem): item is SidebarItemDoc {
  return item.type === 'doc';
}

function isCategoryWithDocLink(item: NormalizedSidebarItem): item is NormalizedSidebarItemCategory & { link: { type: 'doc'; id: string } } {
  return item.type === 'category' && item.link !== undefined && item.link.type === 'doc';
}

/**
 * Post-processes Docusaurus autogenerated sidebar items to match the legacy
 * Reddit wiki navigation shape.
 *
 * Why this exists:
 * - In this docs structure, many categories are linkable via `link: { type: 'doc' }`
 *   and that linked doc is also present as a standalone `doc` item.
 * - The default autogenerated sidebar keeps both entries, which creates visually
 *   duplicated navigation targets (one top-level doc + one category link).
 *
 * What this does:
 * - Finds all category-linked doc IDs.
 * - Removes standalone `doc` items whose IDs are already used as category links.
 *
 * Result:
 * - Cleaner sidebar with one canonical entry point per section, while preserving
 *   the autogenerated ordering and nesting for everything else.
 */
function updateAutogeneratedSidebarForRedditWikiStructure(items: NormalizedSidebar): NormalizedSidebar {
  const docIdsReferencedByCategoryLinks = new Set(
    items.filter(isCategoryWithDocLink).map(item => item.link.id),
  );

  return items.filter(item => !isSidebarDocItem(item) || !docIdsReferencedByCategoryLinks.has(item.id));
}
